# Generated by Django 4.2.10 on 2026-03-03 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_student_data(apps, schema_editor):
    """Populate unique emails and roll numbers for existing students"""
    StudentProfile = apps.get_model('student_app', 'StudentProfile')
    for idx, student in enumerate(StudentProfile.objects.all(), start=1):
        student.email = f"student{idx}@temp.example.com"
        student.roll_number = f"ROLL{idx:04d}"
        student.is_approved = True  # Auto-approve existing students
        student.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(default='temp@example.com', help_text='Email address for notifications and password reset', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval status'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(default='TEMP001', help_text='Student roll number', max_length=20),
            preserve_default=False,
        ),
        migrations.RunPython(populate_student_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(help_text='Email address for notifications and password reset', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(help_text='Student roll number', max_length=20, unique=True),
        ),
    ]
