# Generated by Django 4.2.10 on 2026-02-28 15:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('min_cgpa', models.FloatField(help_text='Minimum CGPA required (0.0 - 10.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('eligible_departments', models.JSONField(default=list, help_text='List of eligible departments')),
                ('eligible_year', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], help_text='Eligible academic year', max_length=1)),
                ('last_date', models.DateTimeField(help_text='Last date to apply')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Draft', 'Draft')], default='Draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_drives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Placement Drive',
                'verbose_name_plural': 'Placement Drives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
            },
        ),
        migrations.CreateModel(
            name='DriveResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('Opt-In', 'Opt-In'), ('Opt-Out', 'Opt-Out')], max_length=10)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='admin_app.drive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drive Response',
                'verbose_name_plural': 'Drive Responses',
                'ordering': ['-responded_at'],
                'unique_together': {('student', 'drive')},
            },
        ),
    ]
