# Generated by Django 4.2.10 on 2026-03-03 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_admin_emails(apps, schema_editor):
    """Populate unique emails for existing admin profiles"""
    AdminProfile = apps.get_model('admin_app', 'AdminProfile')
    for idx, admin in enumerate(AdminProfile.objects.all(), start=1):
        admin.email = f"admin{idx}@temp.example.com"
        admin.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0002_adminprofile_department_adminprofile_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='email',
            field=models.EmailField(default='temp@example.com', help_text='Email address for notifications and password reset', max_length=254),
            preserve_default=False,
        ),
        migrations.RunPython(populate_admin_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='adminprofile',
            name='email',
            field=models.EmailField(help_text='Email address for notifications and password reset', max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='DriveResponseReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_count', models.IntegerField(default=0)),
                ('last_reminder_sent', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='admin_app.drive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drive Response Reminder',
                'verbose_name_plural': 'Drive Response Reminders',
                'ordering': ['-last_reminder_sent'],
                'unique_together': {('student', 'drive')},
            },
        ),
    ]
