# Generated by Django 4.2.10 on 2026-03-08 17:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0004_alter_adminprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', help_text='Email backend to use', max_length=100)),
                ('email_host', models.CharField(default='smtp.gmail.com', help_text='SMTP server hostname', max_length=100)),
                ('email_port', models.IntegerField(default=587, help_text='SMTP server port', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('email_use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('email_host_user', models.EmailField(blank=True, help_text='SMTP username (usually your Gmail address)', max_length=254)),
                ('email_host_password', models.CharField(blank=True, help_text='SMTP password (Gmail App Password recommended)', max_length=255)),
                ('default_from_email', models.EmailField(default='noreply@digitalnoticeboard.com', help_text='Default sender email address', max_length=254)),
                ('reminder_enabled', models.BooleanField(default=True, help_text='Enable automatic email reminders')),
                ('reminder_interval_hours', models.IntegerField(default=1, help_text='Hours between reminder emails (1-24)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('max_reminders', models.IntegerField(default=5, help_text='Maximum number of reminders to send per drive', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('site_url', models.URLField(default='http://localhost:8000', help_text='Base URL of the application')),
                ('site_name', models.CharField(default='Digital Notice Board', help_text='Name of the application', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last admin who updated settings', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
