# Generated by Django 4.2.10 on 2026-03-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='last_reminder_run',
            field=models.DateTimeField(blank=True, help_text='Last time automated reminders were sent', null=True),
        ),
    ]
