# Generated by Django 4.2.10 on 2026-03-10 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_systemsettings_last_reminder_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='reminder_interval_minutes',
            field=models.IntegerField(default=0, help_text='Additional minutes between reminder emails (0-59)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
    ]
